<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>70b7cfbf-cd69-48fe-b583-1ed5d744565f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Search&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>424b475f-4a53-41ae-9d2e-d268154911a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>9041aa83-136a-45f4-b29c-154d3747c53a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>8b2728ab-33f6-46ba-8b91-4dae1578e395</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-fbugsh ant-btn-primary ant-btn-color-primary ant-btn-variant-solid ant-btn-block shadow-none   !text-base text-textBaseWhiteLight dark:text-textBaseDarkDark !leading-6 !h-14 bg-surfaceBasePrimaryLight dark:bg-surfaceBasePrimaryDark</value>
      <webElementGuid>f3b0f6ad-8b91-4229-96e1-02994f2e45e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>9948618f-3a3d-4473-be56-e196f0af039e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tailwind-core&quot;)/body[@class=&quot;__className_a37cae layout_customScrollbar__E0DvH !w-full&quot;]/div[@class=&quot;css-1to9m9p ant-app&quot;]/main[@class=&quot;bg-surfaceBaseWhiteLight dark:bg-surfaceBaseWhiteDark min-h-full min-w-full&quot;]/main[@class=&quot;min-h-screen max-w-full overflow-hidden&quot;]/section[@class=&quot;relative w-full h-[720px] md:h-[840px] lg:h-[720px] bg-no-repeat bg-cover&quot;]/div[@class=&quot;container mx-auto relative z-30 h-full w-full&quot;]/div[2]/div[@class=&quot;relative&quot;]/div[@class=&quot;bg-surfaceBaseDarkLight dark:bg-surfaceBaseBg5Dark bg-opacity-40 dark:bg-opacity-40 py-4 sm:py-8 px-4 rounded-lg md:rounded-ss-none&quot;]/form[@class=&quot;w-full&quot;]/div[@class=&quot;flex flex-col lg:flex-row justify-center items-center gap-2 z-10 w-full&quot;]/div[@class=&quot;flex-1 self-stretch lg:self-auto absolute -bottom-8 w-[298px] h-14 left-1/2 transform translate-x-[-50%]&quot;]/button[@class=&quot;ant-btn css-fbugsh ant-btn-primary ant-btn-color-primary ant-btn-variant-solid ant-btn-block shadow-none   !text-base text-textBaseWhiteLight dark:text-textBaseDarkDark !leading-6 !h-14 bg-surfaceBasePrimaryLight dark:bg-surfaceBasePrimaryDark&quot;]</value>
      <webElementGuid>824ba7de-5023-4b24-bd77-e67466c6961a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>88748695-c063-49e5-be86-81c8ccfd18d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='tailwind-core']/body/div[3]/main/main/section[2]/div[3]/div[2]/div[2]/div/form/div/div[4]/button</value>
      <webElementGuid>125555af-903d-4c39-90ee-c19e3f2f6775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guest'])[1]/following::button[1]</value>
      <webElementGuid>e5f88a28-6504-4dba-a628-a6757e35d657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May 27, 25'])[1]/following::button[2]</value>
      <webElementGuid>28fa4164-c03a-46b9-a6db-30e66d0b11b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Traveling For Business'])[1]/preceding::button[1]</value>
      <webElementGuid>13b1fa9a-3c03-4298-b0af-e1117483023d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>e260dc25-47cf-436e-b589-155ded6ef281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>22f96c27-286e-48e8-b4a1-587b13fb0c10</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
