<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Vacation Rental_rc_select_0</name>
   <tag></tag>
   <elementGuidId>c0127492-7fb6-4cec-9ef3-6226e4aff7fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#rc_select_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='rc_select_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Where do you wanna go?&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b6088fa-6dc0-41a9-8235-e74d22ba0ca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>228a5047-80d6-400f-9afd-21f58abc88a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Where do you wanna go?</value>
      <webElementGuid>06fac0cf-f0ab-48c8-9de1-a46030a97a17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>df0a4bea-acb6-4299-8107-fd6987e25f95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>73f466ba-3402-4e04-a8aa-cda25d8da0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>1d464f8c-7e7d-4956-9050-d6a94a0cec6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-owns</name>
      <type>Main</type>
      <value>rc_select_0_list</value>
      <webElementGuid>57314ba0-e99f-4a30-a48e-e9527d356e52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-autocomplete</name>
      <type>Main</type>
      <value>list</value>
      <webElementGuid>22f039d1-f090-4c6b-9d0a-6153b7e9fe4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>rc_select_0_list</value>
      <webElementGuid>7ba7bc7f-2ddc-4472-a4c1-75ecd9863987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d3454f68-800c-4408-a1cf-7ee9c19392ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input text-sm font-medium !rounded-lg placeholder:!text-textBaseGreyhighLight dark:placeholder:!text-textBaseGreyhighDark !text-textBaseDarkLight dark:!text-textBaseDarkDark !px-2 !pe-0 !leading-[22px]  !py-4 md:!py-6 css-1ddi4ch</value>
      <webElementGuid>866b92a1-fa7f-4c0d-91e7-179db802be50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>ed8f7ce2-7741-44b8-b465-e3cd8b33d229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>rc_select_0</value>
      <webElementGuid>3cdc5b79-9ec9-4ed2-a72f-6c0fccc7fc8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rc_select_0&quot;)</value>
      <webElementGuid>4bf9ec77-7ab2-4afe-a7a9-65dad7487668</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='rc_select_0']</value>
      <webElementGuid>589512b4-2a36-4935-aaf8-e1879195b7b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='widget-destination-input']/section/div/div/div/div/span/span/span/input</value>
      <webElementGuid>f4cfffb6-46c4-48c2-92a3-56d039084138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>751fae0b-c22f-4672-8331-da2fee43cc64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Where do you wanna go?' and @type = 'search' and @id = 'rc_select_0']</value>
      <webElementGuid>4fcc5ef3-877b-4ea2-ba63-764d6fe28ec5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
