<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_1 Night</name>
   <tag></tag>
   <elementGuidId>6b274223-ed70-4890-8e25-ed6b1074a4c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='widget-date-input']/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Monday May 26, 25 1 Night Tuesday May 27, 25 May 2025 MON TUE WED THU FRI SAT SUN 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 Memorial Day 26 27 28 29 30 Dragon Boat Festival 31 June 2025 MON TUE WED THU FRI SAT SUN Children's Day (Partial holiday for some) 01 Dragon Boat Festival Holiday 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 Juneteenth National Independence Day 19 20 21 22 23 24 25 26 27 28 29 30 Holidays&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b5de1df6-38ae-47a0-a252-2d0df2c28bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>1 Night</value>
      <webElementGuid>35443fc1-0242-4d01-9bda-e120887f8c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>m-0 truncate text-textBaseGrayLight dark:text-textBaseGrayDark text-[10px] md:text-xs not-italic font-normal</value>
      <webElementGuid>1e5e2a95-56a8-4802-84e2-a53994e44e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Night</value>
      <webElementGuid>4225f7c9-41b9-4a4b-8cc9-3d37f58f7b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widget-date-input&quot;)/div[@class=&quot;w-fit flex justify-center border border-borderBaseGreylightLight dark:border-borderBaseGreylightDark bg-transparent rounded&quot;]/div[@class=&quot;flex gap-1 items-center px-2 py-1 rounded min-w-fit&quot;]/p[@class=&quot;m-0 truncate text-textBaseGrayLight dark:text-textBaseGrayDark text-[10px] md:text-xs not-italic font-normal&quot;]</value>
      <webElementGuid>255340ac-c0de-41f9-9847-80cd7395abfe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='widget-date-input']/div/div/p</value>
      <webElementGuid>d658973f-3def-406d-ab98-039b55fde6ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May 26, 25'])[1]/following::p[1]</value>
      <webElementGuid>32090d0b-3915-448f-81f2-8a333a5bb3ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monday'])[1]/following::p[1]</value>
      <webElementGuid>2c9b9ffb-ab98-41c1-85ee-3a67848405e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tuesday'])[1]/preceding::p[1]</value>
      <webElementGuid>ebeacbbf-1a14-433a-beb3-6364c8a18d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May 27, 25'])[1]/preceding::p[1]</value>
      <webElementGuid>f6ce7a4d-bb31-47d5-90f7-25af4d5d27aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>c55f19c1-e8eb-42aa-907d-081b82f086e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/p</value>
      <webElementGuid>248385b3-9b95-40f3-a659-d531859bbf86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[@title = '1 Night' and (text() = '1 Night' or . = '1 Night')]</value>
      <webElementGuid>b638f697-f8fc-41a3-90f2-6f0bfd0528f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
