<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Search</name>
   <tag></tag>
   <elementGuidId>c3cdc494-d90a-4c9c-97dc-dc6d5e0e6cd1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Search&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>57812074-b582-4511-8350-d1d21188e028</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>f5b12323-01af-4a3d-a70f-73f4467a543e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>fcd5b367-8d6e-4cbf-8401-6c34495f8685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn css-fbugsh ant-btn-primary ant-btn-color-primary ant-btn-variant-solid ant-btn-block shadow-none   !text-base text-textBaseWhiteLight dark:text-textBaseDarkDark !leading-6 !h-14 bg-surfaceBasePrimaryLight dark:bg-surfaceBasePrimaryDark</value>
      <webElementGuid>043bad2f-9494-40ec-ab5c-0b73763072ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>62b7e0c4-baac-474e-a981-f8f38ec81ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tailwind-core&quot;)/body[@class=&quot;__className_a37cae layout_customScrollbar__E0DvH !w-full&quot;]/div[@class=&quot;css-1to9m9p ant-app&quot;]/main[@class=&quot;bg-surfaceBaseWhiteLight dark:bg-surfaceBaseWhiteDark min-h-full min-w-full&quot;]/main[@class=&quot;min-h-screen max-w-full overflow-hidden&quot;]/section[@class=&quot;relative w-full h-[720px] md:h-[840px] lg:h-[720px] bg-no-repeat bg-cover&quot;]/div[@class=&quot;container mx-auto relative z-30 h-full w-full&quot;]/div[2]/div[@class=&quot;relative&quot;]/div[@class=&quot;bg-surfaceBaseDarkLight dark:bg-surfaceBaseBg5Dark bg-opacity-40 dark:bg-opacity-40 py-4 sm:py-8 px-4 rounded-lg md:rounded-ss-none&quot;]/form[@class=&quot;w-full&quot;]/div[@class=&quot;flex flex-col lg:flex-row justify-center items-center gap-2 z-10 w-full&quot;]/div[@class=&quot;flex-1 self-stretch lg:self-auto absolute -bottom-8 w-[298px] h-14 left-1/2 transform translate-x-[-50%]&quot;]/button[@class=&quot;ant-btn css-fbugsh ant-btn-primary ant-btn-color-primary ant-btn-variant-solid ant-btn-block shadow-none   !text-base text-textBaseWhiteLight dark:text-textBaseDarkDark !leading-6 !h-14 bg-surfaceBasePrimaryLight dark:bg-surfaceBasePrimaryDark&quot;]</value>
      <webElementGuid>d070ad2b-e8b1-4f27-b999-08d2ae3e3024</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>a06eeddf-fc9a-415a-88db-a29e3713e8fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//html[@id='tailwind-core']/body/div[3]/main/main/section[2]/div[3]/div[2]/div[2]/div/form/div/div[4]/button</value>
      <webElementGuid>c8b50463-61b7-40fd-ad26-14dc9c59aefc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guest'])[1]/following::button[1]</value>
      <webElementGuid>075747c5-cbc3-4a24-ab4a-72786d57a7ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='May 27, 25'])[1]/following::button[2]</value>
      <webElementGuid>a64988b9-0484-40cf-90c4-513954f19d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Traveling For Business'])[1]/preceding::button[1]</value>
      <webElementGuid>2991a63e-8967-4711-9411-b1a623a18ec3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>58c11158-6148-4463-b195-c3d0efe9e0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>65f133df-e98d-4bf0-813a-0b3863cb9c4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
