<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Apply</name>
   <tag></tag>
   <elementGuidId>f04ef98e-1d0f-4dd0-9229-36afc926c467</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=':r18:']/div/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Apply&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>81c5a858-77b2-44a0-bc4e-790df99e2f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply</value>
      <webElementGuid>66b30577-e81f-4427-9552-d7f129761b16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:r18:&quot;)/div[@class=&quot;ant-popover-inner-content&quot;]/div[@class=&quot;min-w-[320px] sm:min-w-[400px]&quot;]/button[@class=&quot;ant-btn css-t63o85 ant-btn-primary ant-btn-color-primary ant-btn-variant-solid shadow-none   w-full mt-3 rounded h-9 text-sm bg-surfaceBasePrimaryLight dark:bg-surfaceBasePrimaryDark text-textBaseWhiteLight dark:text-textBaseDarkDark border-none outline-0&quot;]/span[1]</value>
      <webElementGuid>61d3e3f7-6a85-4130-ae2f-88907aba606e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id=':r18:']/div/div/button/span</value>
      <webElementGuid>bec09b91-41a8-438a-813e-22143c8378a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='THB'])[1]/following::span[1]</value>
      <webElementGuid>80ac1779-8550-4303-a0fe-c774721f64f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select Currency'])[1]/following::span[4]</value>
      <webElementGuid>4c295b6f-24df-4dba-83b7-4d78083ee39f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Travel the World'])[1]/preceding::span[1]</value>
      <webElementGuid>c4e01e68-60fd-4161-8e55-202661ec17c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='one adventure at a time'])[1]/preceding::span[1]</value>
      <webElementGuid>be45ddc1-c79e-4f96-bc57-91f97fdf533a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply']/parent::*</value>
      <webElementGuid>2dfcb842-07c2-4c4d-ba5b-733655ebb298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/button/span</value>
      <webElementGuid>ab2df5a3-19c9-4ab5-8cdd-9454f79e9022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Apply' or . = 'Apply')]</value>
      <webElementGuid>05e5abf8-cc49-4800-9a4d-0f33c4572f93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
